// Package restore turns an audit record set into reinstall artifacts —
// a Homebrew Brewfile, a `mas list` file, and a per-app
// manual-restore checklist (RESTORE.md).
package restore

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/simtabi/osaat/internal/audit"
)

// WriteBrewfile emits a Homebrew Brewfile covering records that are
// installable via `brew bundle install`. Casks and Mac App Store apps
// (when their ID is known) are included; everything else is silently
// skipped — the RESTORE.md generator covers the long tail.
func WriteBrewfile(records []audit.AppRecord, w io.Writer) error {
	type brewLine struct {
		kind string
		body string
	}
	var lines []brewLine

	for _, r := range records {
		switch {
		case r.Source == audit.SourceBrewCask:
			cask := extractCaskName(r.ReinstallCmd)
			if cask == "" {
				continue
			}
			lines = append(lines, brewLine{kind: "cask", body: fmt.Sprintf("cask %q", cask)})
		case r.Source == audit.SourceAppStore && r.AppStoreID != "":
			body := fmt.Sprintf("mas %q, id: %s", r.Name, r.AppStoreID)
			lines = append(lines, brewLine{kind: "mas", body: body})
		}
	}

	sort.SliceStable(lines, func(i, j int) bool {
		if lines[i].kind != lines[j].kind {
			return lines[i].kind < lines[j].kind
		}
		return lines[i].body < lines[j].body
	})

	var b strings.Builder
	b.WriteString("# Brewfile generated by osaat\n")
	b.WriteString("# Run `brew bundle --file=./Brewfile` on the new machine.\n\n")

	var lastKind string
	for _, ln := range lines {
		if ln.kind != lastKind {
			if lastKind != "" {
				b.WriteString("\n")
			}
			lastKind = ln.kind
		}
		b.WriteString(ln.body)
		b.WriteString("\n")
	}

	_, err := io.WriteString(w, b.String())
	return err
}

func extractCaskName(reinstallCmd string) string {
	const prefix = "brew install --cask "
	if !strings.HasPrefix(reinstallCmd, prefix) {
		return ""
	}
	return strings.TrimSpace(strings.TrimPrefix(reinstallCmd, prefix))
}
