package restore

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/simtabi/osaat/internal/audit"
)

// WriteAptList emits an `apt-packages.txt` covering every record
// with Source == dpkg. Each package name appears once, sorted. The
// header documents the consume-side command.
func WriteAptList(records []audit.AppRecord, w io.Writer) error {
	return writeLinuxList(w, records, audit.SourceDpkg, "apt-packages.txt", "apt", "sudo apt install -y")
}

// WriteDnfList emits a `dnf-packages.txt` covering every record
// with Source == rpm.
func WriteDnfList(records []audit.AppRecord, w io.Writer) error {
	return writeLinuxList(w, records, audit.SourceRpm, "dnf-packages.txt", "dnf", "sudo dnf install -y")
}

// WritePacmanList emits a `pacman-packages.txt` covering every
// record with Source == pacman.
func WritePacmanList(records []audit.AppRecord, w io.Writer) error {
	return writeLinuxList(w, records, audit.SourcePacman, "pacman-packages.txt", "pacman", "sudo pacman -S --needed")
}

// WriteSnapList emits a `snap-list.txt` covering every record with
// Source == snap. The output is human-readable rather than directly
// xargs-able because some snaps need explicit channels.
func WriteSnapList(records []audit.AppRecord, w io.Writer) error {
	var lines []string
	for _, r := range records {
		if r.Source == audit.SourceSnap {
			if r.ReinstallCmd != "" {
				lines = append(lines, r.ReinstallCmd)
			}
		}
	}
	if len(lines) == 0 {
		return nil
	}
	sort.Strings(lines)

	var b strings.Builder
	b.WriteString("# snap-list.txt generated by osaat\n")
	b.WriteString("# Run each line on the new machine.\n\n")
	for _, ln := range lines {
		b.WriteString(ln)
		b.WriteString("\n")
	}
	_, err := io.WriteString(w, b.String())
	return err
}

// WriteFlatpakList emits a `flatpak-list.txt` with one
// `flatpak install` command per app.
func WriteFlatpakList(records []audit.AppRecord, w io.Writer) error {
	var lines []string
	for _, r := range records {
		if r.Source == audit.SourceFlatpak && r.ReinstallCmd != "" {
			lines = append(lines, r.ReinstallCmd)
		}
	}
	if len(lines) == 0 {
		return nil
	}
	sort.Strings(lines)

	var b strings.Builder
	b.WriteString("# flatpak-list.txt generated by osaat\n")
	b.WriteString("# Run each line on the new machine after `flatpak remote-add` setup.\n\n")
	for _, ln := range lines {
		b.WriteString(ln)
		b.WriteString("\n")
	}
	_, err := io.WriteString(w, b.String())
	return err
}

// writeLinuxList is the shared helper for apt / dnf / pacman lists.
func writeLinuxList(w io.Writer, records []audit.AppRecord, src audit.Source, filename, tool, install string) error {
	var pkgs []string
	seen := map[string]struct{}{}
	for _, r := range records {
		if r.Source != src || r.PkgID == "" {
			continue
		}
		if _, dup := seen[r.PkgID]; dup {
			continue
		}
		seen[r.PkgID] = struct{}{}
		pkgs = append(pkgs, r.PkgID)
	}
	if len(pkgs) == 0 {
		return nil
	}
	sort.Strings(pkgs)

	var b strings.Builder
	fmt.Fprintf(&b, "# %s generated by osaat for the %s package manager\n", filename, tool)
	fmt.Fprintln(&b, "# On the new machine:")
	fmt.Fprintf(&b, "#   xargs -a %s %s\n\n", filename, install)
	for _, p := range pkgs {
		b.WriteString(p)
		b.WriteString("\n")
	}
	_, err := io.WriteString(w, b.String())
	return err
}

// HasSource reports whether records contains at least one entry
// from the given source. Exported so the manifest orchestrator can
// gate emission on relevance.
func HasSource(records []audit.AppRecord, src audit.Source) bool {
	for _, r := range records {
		if r.Source == src {
			return true
		}
	}
	return false
}
