package restore

import (
	"bytes"
	"strings"
	"testing"

	"github.com/simtabi/osaat/internal/audit"
)

func linuxFixtureRecords() []audit.AppRecord {
	return []audit.AppRecord{
		{Name: "bash", PkgID: "bash", Source: audit.SourceDpkg, ReinstallCmd: "apt install bash"},
		{Name: "curl", PkgID: "curl", Source: audit.SourceDpkg},
		{Name: "kernel", PkgID: "kernel", Source: audit.SourceRpm},
		{Name: "vim", PkgID: "vim", Source: audit.SourcePacman},
		{Name: "firefox", PkgID: "firefox", Source: audit.SourceSnap, ReinstallCmd: "snap install firefox"},
		{Name: "Flatseal", PkgID: "com.github.tchx84.Flatseal", Source: audit.SourceFlatpak, ReinstallCmd: "flatpak install -y flathub com.github.tchx84.Flatseal"},
		// Duplicate dpkg name to test dedup
		{Name: "bash", PkgID: "bash", Source: audit.SourceDpkg},
		// Non-Linux record — should be skipped by every Linux writer
		{Name: "Safari", Source: audit.SourceSystem},
	}
}

func TestWriteAptList(t *testing.T) {
	var buf bytes.Buffer
	if err := WriteAptList(linuxFixtureRecords(), &buf); err != nil {
		t.Fatal(err)
	}
	out := buf.String()
	for _, want := range []string{
		"apt-packages.txt generated by osaat",
		"sudo apt install -y",
		"\nbash\n",
		"\ncurl\n",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("apt list missing %q\n--- output ---\n%s", want, out)
		}
	}
	// bash duplicated in input — should appear once
	if strings.Count(out, "\nbash\n") != 1 {
		t.Errorf("bash should appear once after dedup; got %d\n%s", strings.Count(out, "\nbash\n"), out)
	}
}

func TestWriteAptListEmptyOnNoDpkg(t *testing.T) {
	macRecords := []audit.AppRecord{{Name: "Safari", Source: audit.SourceSystem}}
	var buf bytes.Buffer
	if err := WriteAptList(macRecords, &buf); err != nil {
		t.Fatal(err)
	}
	if buf.Len() != 0 {
		t.Errorf("apt list should be empty when no dpkg records; got %q", buf.String())
	}
}

func TestWriteDnfList(t *testing.T) {
	var buf bytes.Buffer
	if err := WriteDnfList(linuxFixtureRecords(), &buf); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(buf.String(), "sudo dnf install -y") {
		t.Errorf("dnf list missing install command:\n%s", buf.String())
	}
	if !strings.Contains(buf.String(), "\nkernel\n") {
		t.Errorf("dnf list missing kernel:\n%s", buf.String())
	}
}

func TestWritePacmanList(t *testing.T) {
	var buf bytes.Buffer
	if err := WritePacmanList(linuxFixtureRecords(), &buf); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(buf.String(), "sudo pacman -S --needed") {
		t.Errorf("pacman list missing install command:\n%s", buf.String())
	}
	if !strings.Contains(buf.String(), "\nvim\n") {
		t.Errorf("pacman list missing vim:\n%s", buf.String())
	}
}

func TestWriteSnapList(t *testing.T) {
	var buf bytes.Buffer
	if err := WriteSnapList(linuxFixtureRecords(), &buf); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(buf.String(), "snap install firefox") {
		t.Errorf("snap list missing firefox install:\n%s", buf.String())
	}
}

func TestWriteFlatpakList(t *testing.T) {
	var buf bytes.Buffer
	if err := WriteFlatpakList(linuxFixtureRecords(), &buf); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(buf.String(), "flatpak install -y flathub com.github.tchx84.Flatseal") {
		t.Errorf("flatpak list missing entry:\n%s", buf.String())
	}
}

func TestHasSource(t *testing.T) {
	recs := linuxFixtureRecords()
	for _, src := range []audit.Source{audit.SourceDpkg, audit.SourceRpm, audit.SourcePacman, audit.SourceSnap, audit.SourceFlatpak} {
		if !HasSource(recs, src) {
			t.Errorf("HasSource(%q) should be true", src)
		}
	}
	if HasSource(recs, audit.SourceAppStore) {
		t.Error("HasSource(app_store) should be false on Linux fixture")
	}
}

func TestWriteAllIncludesLinuxLists(t *testing.T) {
	dir := t.TempDir()
	paths, err := WriteAll(linuxFixtureRecords(), dir)
	if err != nil {
		t.Fatal(err)
	}
	names := map[string]bool{}
	for _, p := range paths {
		names[lastPathSegment(p)] = true
	}
	for _, want := range []string{
		"Brewfile",
		"mas-apps.txt",
		"apt-packages.txt",
		"dnf-packages.txt",
		"pacman-packages.txt",
		"snap-list.txt",
		"flatpak-list.txt",
		"RESTORE.md",
	} {
		if !names[want] {
			t.Errorf("WriteAll should have produced %q (got %v)", want, names)
		}
	}
}

func TestWriteAllSkipsLinuxListsOnMacOnly(t *testing.T) {
	dir := t.TempDir()
	macRecords := []audit.AppRecord{
		{Name: "1Password", Source: audit.SourceBrewCask, ReinstallCmd: "brew install --cask 1password"},
	}
	paths, err := WriteAll(macRecords, dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, p := range paths {
		seg := lastPathSegment(p)
		if strings.HasSuffix(seg, "packages.txt") || strings.HasSuffix(seg, "-list.txt") {
			t.Errorf("macOS-only scan should not produce %s", seg)
		}
	}
}

func lastPathSegment(p string) string {
	for i := len(p) - 1; i >= 0; i-- {
		if p[i] == '/' || p[i] == '\\' {
			return p[i+1:]
		}
	}
	return p
}
