package restore

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/simtabi/osaat/internal/audit"
)

// WriteMasList emits a plain-text file with one Mac App Store app ID
// per line. Consumed by:
//
//	xargs -L1 mas install < mas-apps.txt
//
// The file is preceded by a comment block with the app name so a human
// can read the list before running it. mas itself ignores comments
// when called via xargs, but you can also pipe through `grep -v '^#'`
// to filter explicitly.
func WriteMasList(records []audit.AppRecord, w io.Writer) error {
	type masEntry struct {
		ID, Name string
	}
	var entries []masEntry
	for _, r := range records {
		if r.Source == audit.SourceAppStore && r.AppStoreID != "" {
			entries = append(entries, masEntry{ID: r.AppStoreID, Name: r.Name})
		}
	}
	sort.SliceStable(entries, func(i, j int) bool {
		return strings.ToLower(entries[i].Name) < strings.ToLower(entries[j].Name)
	})

	var b strings.Builder
	b.WriteString("# mas-apps.txt generated by osaat\n")
	b.WriteString("# On the new machine, after `mas signin`:\n")
	b.WriteString("#   grep -v '^#' mas-apps.txt | awk '{print $1}' | xargs -L1 mas install\n\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "%s  # %s\n", e.ID, e.Name)
	}
	_, err := io.WriteString(w, b.String())
	return err
}
